# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
